"""Generate ``.env.example`` from the settings model (ADR-0015, R-112).

A hand-maintained example file falls out of date the first time someone adds a variable
in a hurry, and a stale one actively misleads whoever sets the project up. Generating it
makes drift structurally impossible, and ``tests/test_structural.py`` asserts the result
still covers every field.

    python scripts/gen_env_example.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from movieagent.config import Settings  # noqa: E402

#: Documentation per variable. Anything absent here still appears, un-annotated, so a new
#: setting cannot silently vanish from the example file.
NOTES: dict[str, str] = {
    "llm_base_url": "Chat/tool-calling endpoint. OpenRouter by default; point at a vLLM server to switch.",
    "llm_api_key": "REQUIRED for the agent. Not needed to build the index or run structured/fuzzy search.",
    "llm_model": "Must support native tool calling.",
    "llm_temperature": "0 keeps routing reproducible.",
    "llm_timeout_s": "Per-request timeout in seconds.",
    "llm_max_retries": "Retries on 429/5xx/timeout, handled by the client (R-087).",
    "embedding_provider": "sentence_transformers (local, default) | openai_compatible",
    "embedding_model": "Changing this invalidates the built index. Rebuild after changing it.",
    "embedding_base_url": (
        "ONLY for embedding_provider=openai_compatible, and INDEPENDENT of LLM_BASE_URL. "
        "OpenRouter serves no /v1/embeddings endpoint -- point this at OpenAI, vLLM, "
        "Ollama or LM Studio."
    ),
    "embedding_api_key": "Only for embedding_provider=openai_compatible.",
    "embedding_batch_size": "Documents per embedding request/batch.",
    "vector_backend": (
        "numpy (in-process exact cosine, default) | qdrant. Both answer identically -- "
        "scripts/benchmark_vector_backends.py measures that they do."
    ),
    "qdrant_collection": "Collection name, for VECTOR_BACKEND=qdrant.",
    "qdrant_url": (
        "Unset means embedded Qdrant in <ARTIFACTS_DIR>/qdrant, which needs no server. "
        "Set it to run against a Qdrant instance instead -- that is the whole migration."
    ),
    "qdrant_api_key": "Only for a served Qdrant that requires authentication.",
    "top_k": "Default number of semantic results.",
    "similarity_floor": (
        "Backstop only. An absolute cosine threshold cannot separate real queries from "
        "gibberish on this corpus (ADR-0026); MIN_LEXICAL_COVERAGE is the real signal."
    ),
    "min_lexical_coverage": (
        "Fraction of a query's content words that must appear in the corpus vocabulary "
        "before retrieval is trusted. Below this, the tool reports low confidence."
    ),
    "result_display_limit": "Rows shown per structured result; the true total is always reported.",
    "fuzzy_accept": "Score at or above which a title match is accepted (ADR-0025).",
    "fuzzy_ambiguous": "Below this, the title is reported as not found.",
    "fuzzy_tie_margin": "If the top two candidates are within this, ask instead of guessing.",
    "fuzzy_max_candidates": "Candidates offered when a title is ambiguous.",
    "recursion_limit": "LangGraph recursion cap for the agent<->tools cycle.",
    "max_tool_iterations": "Hard cap on tool calls per turn.",
    "turn_timeout_s": "Wall-clock budget for one turn.",
    "message_window": "Raw chat messages kept in state; structured memory carries the rest.",
    "data_dir": "Where the TMDB CSVs live.",
    "artifacts_dir": (
        "Where the build step writes movies.parquet, embeddings.npy, manifest.json and "
        "the embedded qdrant/ directory."
    ),
    "log_level": "DEBUG | INFO | WARNING | ERROR",
    "log_file": "Optional path for a log file; stderr only when unset.",
}

#: Optional settings that should still appear uncommented, because the user is meant
#: to fill them in. Everything else with no default is commented out.
_MUST_PROMPT = {"llm_api_key"}

GROUPS: list[tuple[str, tuple[str, ...]]] = [
    ("LLM — chat and tool calling (R-117)", ("llm_",)),
    ("Embeddings — independent of the LLM endpoint (R-118, ADR-0007)", ("embedding_",)),
    ("Vector store (ADR-0006)", ("vector_backend", "qdrant_")),
    ("Retrieval (ADR-0011, ADR-0026)", ("top_k", "similarity_floor", "min_lexical", "result_display")),
    ("Fuzzy title matching (ADR-0025)", ("fuzzy_",)),
    ("Agent loop guards (ADR-0021, ADR-0022)", ("recursion_", "max_tool_", "turn_timeout", "message_window")),
    ("Paths", ("data_dir", "artifacts_dir")),
    ("Logging", ("log_",)),
]


def render() -> str:
    fields = dict(Settings.model_fields)
    lines = [
        "# Environment configuration for the TMDB movie agent.",
        "#",
        "# GENERATED by scripts/gen_env_example.py from movieagent.config.Settings.",
        "# Do not hand-edit: regenerate instead, or the file drifts from the code (R-112).",
        "#",
        "# Copy to .env and fill in what you need. Everything has a working default except",
        "# LLM_API_KEY -- and the deterministic half of the system (preprocessing,",
        "# structured search, fuzzy matching, local embeddings) runs without even that.",
        "",
    ]

    used: set[str] = set()
    for title, prefixes in GROUPS:
        members = [n for n in fields if n.startswith(prefixes) and n not in used]
        if not members:
            continue
        used.update(members)
        lines.append(f"# {'-' * 74}")
        lines.append(f"# {title}")
        lines.append(f"# {'-' * 74}")
        for name in members:
            lines.extend(_render_field(name, fields[name]))
        lines.append("")

    leftover = [n for n in fields if n not in used]
    if leftover:
        lines.append("# Other")
        for name in leftover:
            lines.extend(_render_field(name, fields[name]))
        lines.append("")

    return "\n".join(lines)


def _render_field(name: str, field: object) -> list[str]:
    out: list[str] = []
    if note := NOTES.get(name):
        for chunk in _wrap(note):
            out.append(f"# {chunk}")
    default = getattr(field, "default", None)
    if default is None or repr(default) == "PydanticUndefined":
        # Emit optional settings *commented out*. A bare `NAME=` is read by dotenv as
        # an empty string rather than as absent, and for a `Path | None` field pydantic
        # turns that into `Path(".")` -- which is how LOG_FILE= once pointed the log
        # handler at the project directory. Credentials stay uncommented so the file
        # still shows where to put them.
        if name in _MUST_PROMPT:
            out.append(f"{name.upper()}=")
        else:
            out.append(f"# {name.upper()}=")
        return out
    rendered = default.value if hasattr(default, "value") else default
    out.append(f"{name.upper()}={rendered}")
    return out


def _wrap(text: str, width: int = 76) -> list[str]:
    words, line, out = text.split(), "", []
    for word in words:
        if len(line) + len(word) + 1 > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(line)
    return out


if __name__ == "__main__":
    target = _ROOT / ".env.example"
    target.write_text(render(), encoding="utf-8")
    print(f"wrote {target}")
