"""Length statistics for the built retrieval documents (``artifacts/documents.parquet``).

Run::

    python scripts/profile_documents.py [--documents artifacts/documents.parquet]
                                        [--out artifacts/document_stats.md]

Document length is what decides whether the embedding model sees a whole document or a
truncated one, so the tail matters as much as the mean: the max tells you how much of a
document can be silently cut, the min tells you which movies carry almost no signal.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

TOP_N = 10


def summarise(series: pd.Series) -> dict[str, float]:
    """Mean/min/max plus the percentiles that show the tail."""
    return {
        "count": int(series.count()),
        "mean": float(series.mean()),
        "median": float(series.median()),
        "min": int(series.min()),
        "max": int(series.max()),
        "p10": float(series.quantile(0.10)),
        "p90": float(series.quantile(0.90)),
        "p99": float(series.quantile(0.99)),
        "std": float(series.std()),
        "total": int(series.sum()),
    }


def fmt(value: float) -> str:
    return f"{value:,.2f}".rstrip("0").rstrip(".") if isinstance(value, float) else f"{value:,}"


def md_table(rows: list[list[object]], headers: list[str]) -> str:
    out = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|") for c in row) + " |")
    return "\n".join(out) + "\n"


def build_report(df: pd.DataFrame, source: Path) -> str:
    text = df["document"].fillna("").astype(str)
    words = text.str.split().str.len()
    chars = text.str.len()
    # Characters excluding whitespace: closer to the actual token-bearing content.
    chars_nows = text.str.replace(r"\s+", "", regex=True).str.len()

    word_stats = summarise(words)
    char_stats = summarise(chars)
    nows_stats = summarise(chars_nows)

    parts: list[str] = []

    def add(line: str) -> None:
        parts.append(line if line.endswith("\n") else line + "\n")

    add("# Retrieval documents - length analysis\n")
    add(f"Generated by `scripts/profile_documents.py` from `{source.as_posix()}`.\n")
    add(f"- Documents: **{fmt(len(df))}**")
    add(f"- Empty documents: {fmt(int((words == 0).sum()))}")
    add("")

    add("## Averages\n")
    add(
        md_table(
            [
                [
                    "words per document",
                    fmt(word_stats["mean"]),
                    fmt(word_stats["median"]),
                    fmt(word_stats["min"]),
                    fmt(word_stats["max"]),
                    fmt(word_stats["std"]),
                    fmt(word_stats["total"]),
                ],
                [
                    "characters per document",
                    fmt(char_stats["mean"]),
                    fmt(char_stats["median"]),
                    fmt(char_stats["min"]),
                    fmt(char_stats["max"]),
                    fmt(char_stats["std"]),
                    fmt(char_stats["total"]),
                ],
                [
                    "characters (no whitespace)",
                    fmt(nows_stats["mean"]),
                    fmt(nows_stats["median"]),
                    fmt(nows_stats["min"]),
                    fmt(nows_stats["max"]),
                    fmt(nows_stats["std"]),
                    fmt(nows_stats["total"]),
                ],
            ],
            ["metric", "mean", "median", "min", "max", "std dev", "total"],
        )
    )
    add("")
    add(f"- Mean characters per word: {fmt(char_stats['total'] / max(word_stats['total'], 1))}")
    add("")

    add("## Distribution of words per document\n")
    add(
        md_table(
            [
                ["p10", fmt(word_stats["p10"])],
                ["median (p50)", fmt(word_stats["median"])],
                ["p90", fmt(word_stats["p90"])],
                ["p99", fmt(word_stats["p99"])],
            ],
            ["percentile", "words"],
        )
    )
    add("")

    frame = pd.DataFrame({"id": df["id"], "words": words, "chars": chars, "text": text})
    shortest = frame.nsmallest(TOP_N, "words")
    longest = frame.nlargest(TOP_N, "words")

    add(f"## {TOP_N} shortest documents\n")
    add(
        md_table(
            [
                [i, r.id, fmt(int(r.words)), fmt(int(r.chars)), r.text.splitlines()[0][:60] if r.text else ""]
                for i, r in enumerate(shortest.itertuples(), 1)
            ],
            ["#", "id", "words", "characters", "first line"],
        )
    )
    add("")

    add(f"## {TOP_N} longest documents\n")
    add(
        md_table(
            [
                [i, r.id, fmt(int(r.words)), fmt(int(r.chars)), r.text.splitlines()[0][:60] if r.text else ""]
                for i, r in enumerate(longest.itertuples(), 1)
            ],
            ["#", "id", "words", "characters", "first line"],
        )
    )

    return "".join(parts)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--documents", type=Path, default=root / "artifacts" / "documents.parquet")
    parser.add_argument("--out", type=Path, default=root / "artifacts" / "document_stats.md")
    args = parser.parse_args()

    if not args.documents.exists():
        print(f"missing documents artifact: {args.documents}", file=sys.stderr)
        print("run `python scripts/build_index.py` first", file=sys.stderr)
        return 1

    df = pd.read_parquet(args.documents)
    report = build_report(df, args.documents)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report, encoding="utf-8")
    print(report)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
